version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5.9
    container_name: etcd
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes  # 允许空密码
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379  # 客户端监听地址
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379  # 客户端访问地址

  mysql:
    image: 'mysql:8.0.33'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=zmall
      - MYSQL_USER=zza
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456  # 设置 root 用户密码

  redis:
    image: 'redis:7.0.11'
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP 协议端口
      - "15672:15672"  # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # 指定ES地址
    ports:
      - "5601:5601"  # Kibana管理界面端口
    networks:
      - default

networks:
    default:
      name: zmall