// Code generated by hertz generator.

package router

import (
	handler "github.com/NJUPTzza/zmall/app/gateway/biz/handler/user"
	"github.com/NJUPTzza/zmall/rpc_gen/kitex_gen/user/userservice"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func userRegister(r *server.Hertz) {

	userClient := userservice.MustNewClient("user_service")

	r.POST("/api/v1/register", handler.Register(userClient))
	r.POST("/api/v1/login", handler.Login(userClient))
	r.GET("/api/v1/getuser", handler.GetUser(userClient))
}
