// Code generated by Kitex v0.9.1. DO NOT EDIT.

package notificationservice

import (
	"context"
	"errors"
	notification "github.com/NJUPTzza/zmall/rpc_gen/kitex_gen/notification"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendNotification": kitex.NewMethodInfo(
		sendNotificationHandler,
		newSendNotificationArgs,
		newSendNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetNotifications": kitex.NewMethodInfo(
		getNotificationsHandler,
		newGetNotificationsArgs,
		newGetNotificationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	notificationServiceServiceInfo                = NewServiceInfo()
	notificationServiceServiceInfoForClient       = NewServiceInfoForClient()
	notificationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return notificationServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "NotificationService"
	handlerType := (*notification.NotificationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "notification",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(notification.SendNotificationRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(notification.NotificationService).SendNotification(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SendNotificationArgs:
		success, err := handler.(notification.NotificationService).SendNotification(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendNotificationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSendNotificationArgs() interface{} {
	return &SendNotificationArgs{}
}

func newSendNotificationResult() interface{} {
	return &SendNotificationResult{}
}

type SendNotificationArgs struct {
	Req *notification.SendNotificationRequest
}

func (p *SendNotificationArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(notification.SendNotificationRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SendNotificationArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SendNotificationArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SendNotificationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendNotificationArgs) Unmarshal(in []byte) error {
	msg := new(notification.SendNotificationRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendNotificationArgs_Req_DEFAULT *notification.SendNotificationRequest

func (p *SendNotificationArgs) GetReq() *notification.SendNotificationRequest {
	if !p.IsSetReq() {
		return SendNotificationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendNotificationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendNotificationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendNotificationResult struct {
	Success *notification.SendNotificationResponse
}

var SendNotificationResult_Success_DEFAULT *notification.SendNotificationResponse

func (p *SendNotificationResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(notification.SendNotificationResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SendNotificationResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SendNotificationResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SendNotificationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendNotificationResult) Unmarshal(in []byte) error {
	msg := new(notification.SendNotificationResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendNotificationResult) GetSuccess() *notification.SendNotificationResponse {
	if !p.IsSetSuccess() {
		return SendNotificationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendNotificationResult) SetSuccess(x interface{}) {
	p.Success = x.(*notification.SendNotificationResponse)
}

func (p *SendNotificationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendNotificationResult) GetResult() interface{} {
	return p.Success
}

func getNotificationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(notification.GetNotificationsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(notification.NotificationService).GetNotifications(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetNotificationsArgs:
		success, err := handler.(notification.NotificationService).GetNotifications(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetNotificationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetNotificationsArgs() interface{} {
	return &GetNotificationsArgs{}
}

func newGetNotificationsResult() interface{} {
	return &GetNotificationsResult{}
}

type GetNotificationsArgs struct {
	Req *notification.GetNotificationsRequest
}

func (p *GetNotificationsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(notification.GetNotificationsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetNotificationsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetNotificationsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetNotificationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetNotificationsArgs) Unmarshal(in []byte) error {
	msg := new(notification.GetNotificationsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetNotificationsArgs_Req_DEFAULT *notification.GetNotificationsRequest

func (p *GetNotificationsArgs) GetReq() *notification.GetNotificationsRequest {
	if !p.IsSetReq() {
		return GetNotificationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetNotificationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetNotificationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetNotificationsResult struct {
	Success *notification.GetNotificationsResponse
}

var GetNotificationsResult_Success_DEFAULT *notification.GetNotificationsResponse

func (p *GetNotificationsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(notification.GetNotificationsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetNotificationsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetNotificationsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetNotificationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetNotificationsResult) Unmarshal(in []byte) error {
	msg := new(notification.GetNotificationsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetNotificationsResult) GetSuccess() *notification.GetNotificationsResponse {
	if !p.IsSetSuccess() {
		return GetNotificationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetNotificationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*notification.GetNotificationsResponse)
}

func (p *GetNotificationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetNotificationsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendNotification(ctx context.Context, Req *notification.SendNotificationRequest) (r *notification.SendNotificationResponse, err error) {
	var _args SendNotificationArgs
	_args.Req = Req
	var _result SendNotificationResult
	if err = p.c.Call(ctx, "SendNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNotifications(ctx context.Context, Req *notification.GetNotificationsRequest) (r *notification.GetNotificationsResponse, err error) {
	var _args GetNotificationsArgs
	_args.Req = Req
	var _result GetNotificationsResult
	if err = p.c.Call(ctx, "GetNotifications", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
