// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/NJUPTzza/zmall/app/gateway/biz/router"
)

func main() {
	h := server.Default()

	router.Register(h)
	h.Spin()
}
