version: '3'
services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes  # 允许空密码
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379  # 客户端监听地址
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379  # 客户端访问地址

  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
